### ISSUE TITLE
Watchlist unvollständig

### ISSUE THREAD

**Issue by claell** [XLordKX/kodi#16]
Aus meiner Filme Watchlist werden leider nur noch die ersten 12 Einträge angezeigt. Entweder liegt es daran, dass mit der Zeit zu viele neue Einträge hinzugekommen sind, oder der Fehler kam mit den letzten Updates vom Addon. Ich meine, dass es mit Version 1.0.23 noch funktioniert hat.

**Comment by claell** [comment]
Nachtrag: Ist auch bei Serien der Fall. Nachdem ich einige einträge hinzugefügt habe (sind jetzt 21 Elemente), werden nur noch 3 Elemente über das Addon angezeigt.

**Comment by XLordKX** [comment]
Korrigiert in 1.0.25

**Comment by claell** [comment]
Boah, das war schnell. Danke!

**Comment by claell** [comment]
Leider noch nicht ganz korrigiert. Bei Filme zeigt er mir jetzt 60 Elemente an, bei Serien 8.

**Comment by XLordKX** [comment]
OK, wird heute abend dann weiter korrigiert :)

**Comment by claell** [comment]
Danke

**Comment by XLordKX** [comment]
Jetzt aber :)

**Comment by claell** [comment]
Ja, passt jetzt. Serien gingen glaube ich vorher auch schon, die andere Anzahl lag an der Gliederung nach Serien im Addon vs. nach Staffeln auf der Website. Vielen Dank noch mal.
